const express = require('express');
const router = express.Router();
const transactionController = require('../controllers/transactionController');

// API Endpoints

// Issue a book
// POST /api/transactions/issue
router.post('/issue', transactionController.issueBook);

// Return a book
// POST /api/transactions/return
router.post('/return', transactionController.returnBook);

// Get list of people who have issued a book in the past
// GET /api/transactions/book/issued-by/:bookName
router.get('/book/issued-by/:bookName', transactionController.getIssuedByBook);

// Get total rent generated by a book
// GET /api/transactions/book/total-rent/:bookName
router.get('/book/total-rent/:bookName', transactionController.getTotalRentByBook);

// Get list of books issued to a person
// GET /api/transactions/person/:userId
router.get('/person/:userId', transactionController.getBooksIssuedToPerson);

// Get list of books issued in a date range
// GET /api/transactions/date-range?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
router.get('/date-range', transactionController.getBooksIssuedInDateRange);

module.exports = router;
